/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Alipay: typeof import('./src/components/oauth/alipay.vue')['default']
    LayoutPage: typeof import('./src/components/layoutPage.vue')['default']
    PvAuth: typeof import('./src/components/oauth/pv-auth.vue')['default']
    PvButton: typeof import('./src/components/public/pv-button.vue')['default']
    PvCode: typeof import('./src/components/public/pv-code.vue')['default']
    PvCustom: typeof import('./src/components/public/pv-custom.vue')['default']
    PvEditor: typeof import('./src/components/public/pv-editor.vue')['default']
    PvForm: typeof import('./src/components/public/pv-form.vue')['default']
    PvFormItem: typeof import('./src/components/public/pv-formItem.vue')['default']
    PvHeader: typeof import('./src/components/public/pv-header.vue')['default']
    PvIcons: typeof import('./src/components/public/pv-icons.vue')['default']
    PvInput: typeof import('./src/components/public/pv-input.vue')['default']
    PvPopup: typeof import('./src/components/public/pv-popup.vue')['default']
    PvRadio: typeof import('./src/components/public/pv-radio.vue')['default']
    PvRandom: typeof import('./src/components/public/pv-random.vue')['default']
    PvScroll: typeof import('./src/components/public/pv-scroll.vue')['default']
    PvSwiper: typeof import('./src/components/public/pv-swiper.vue')['default']
    PvSwitch: typeof import('./src/components/public/pv-switch.vue')['default']
    PvTcp: typeof import('./src/components/public/pv-tcp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Weixin: typeof import('./src/components/oauth/weixin.vue')['default']
  }
}
